// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace WispTestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        #region Properties
        public UIWISPПодключитевашихсWindow UIWISPПодключитевашихсWindow
        {
            get
            {
                if ((this.mUIWISPПодключитевашихсWindow == null))
                {
                    this.mUIWISPПодключитевашихсWindow = new UIWISPПодключитевашихсWindow();
                }
                return this.mUIWISPПодключитевашихсWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIWISPПодключитевашихсWindow mUIWISPПодключитевашихсWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIWISPПодключитевашихсWindow : BrowserWindow
    {
        
        public UIWISPПодключитевашихсWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "WISP - Подключите ваших сотрудников к корпоративной жизни";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
            this.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIWISPПодключитевашихсDocument UIWISPПодключитевашихсDocument
        {
            get
            {
                if ((this.mUIWISPПодключитевашихсDocument == null))
                {
                    this.mUIWISPПодключитевашихсDocument = new UIWISPПодключитевашихсDocument(this);
                }
                return this.mUIWISPПодключитевашихсDocument;
            }
        }
        
        public UIWispConnectyouremploDocument UIWispConnectyouremploDocument
        {
            get
            {
                if ((this.mUIWispConnectyouremploDocument == null))
                {
                    this.mUIWispConnectyouremploDocument = new UIWispConnectyouremploDocument(this);
                }
                return this.mUIWispConnectyouremploDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIWISPПодключитевашихсDocument mUIWISPПодключитевашихсDocument;
        
        private UIWispConnectyouremploDocument mUIWispConnectyouremploDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIWISPПодключитевашихсDocument : HtmlDocument
    {
        
        public UIWISPПодключитевашихсDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "WISP - Подключите ваших сотрудников к корпоративной жизни";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://agaveqa.inside.cactussoft.biz/";
            this.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
            this.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIВходENБезопасностьТаPane
        {
            get
            {
                if ((this.mUIВходENБезопасностьТаPane == null))
                {
                    this.mUIВходENБезопасностьТаPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIВходENБезопасностьТаPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIВходENБезопасностьТаPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIВходENБезопасностьТаPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Вход EN БезопасностьТарифы ";
                    this.mUIВходENБезопасностьТаPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIВходENБезопасностьТаPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "header-stripe";
                    this.mUIВходENБезопасностьТаPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"header-stripe\"";
                    this.mUIВходENБезопасностьТаPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "2";
                    this.mUIВходENБезопасностьТаPane.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
                    this.mUIВходENБезопасностьТаPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIВходENБезопасностьТаPane;
            }
        }
        
        public HtmlDiv UIВходENБезопасностьТаPane1
        {
            get
            {
                if ((this.mUIВходENБезопасностьТаPane1 == null))
                {
                    this.mUIВходENБезопасностьТаPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIВходENБезопасностьТаPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIВходENБезопасностьТаPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIВходENБезопасностьТаPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Вход EN БезопасностьТарифы \r\n\r\n\r\nСоздайт";
                    this.mUIВходENБезопасностьТаPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIВходENБезопасностьТаPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = "header-area";
                    this.mUIВходENБезопасностьТаPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"header-area\"";
                    this.mUIВходENБезопасностьТаPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
                    this.mUIВходENБезопасностьТаPane1.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
                    this.mUIВходENБезопасностьТаPane1.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIВходENБезопасностьТаPane1;
            }
        }
        
        public HtmlDiv UIФункционалПерсонализPane
        {
            get
            {
                if ((this.mUIФункционалПерсонализPane == null))
                {
                    this.mUIФункционалПерсонализPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIФункционалПерсонализPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIФункционалПерсонализPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIФункционалПерсонализPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Функционал:\r\n\r\nПерсонализируйте приложен";
                    this.mUIФункционалПерсонализPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIФункционалПерсонализPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "features-area";
                    this.mUIФункционалПерсонализPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"features-area\"";
                    this.mUIФункционалПерсонализPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "15";
                    this.mUIФункционалПерсонализPane.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
                    this.mUIФункционалПерсонализPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIФункционалПерсонализPane;
            }
        }
        
        public HtmlDiv UIItem1ПерсонализацияСPane
        {
            get
            {
                if ((this.mUIItem1ПерсонализацияСPane == null))
                {
                    this.mUIItem1ПерсонализацияСPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItem1ПерсонализацияСPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItem1ПерсонализацияСPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItem1ПерсонализацияСPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "1\r\n\r\nПерсонализация\r\n\r\nСделайте ваше при";
                    this.mUIItem1ПерсонализацияСPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItem1ПерсонализацияСPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "slide-area";
                    this.mUIItem1ПерсонализацияСPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"slide-area\"";
                    this.mUIItem1ПерсонализацияСPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "17";
                    this.mUIItem1ПерсонализацияСPane.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
                    this.mUIItem1ПерсонализацияСPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItem1ПерсонализацияСPane;
            }
        }
        
        public HtmlHyperlink UIТарифыHyperlink
        {
            get
            {
                if ((this.mUIТарифыHyperlink == null))
                {
                    this.mUIТарифыHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIТарифыHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIТарифыHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIТарифыHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIТарифыHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Тарифы";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/admin/";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Тарифы";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://agaveqa.inside.cactussoft.biz/admin/#/tariffplans";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "pull-right cross-link";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Тарифы\" class=\"pull-right cross-l";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "5";
                    this.mUIТарифыHyperlink.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIТарифыHyperlink;
            }
        }
        
        public HtmlHyperlink UIБезопасностьHyperlink
        {
            get
            {
                if ((this.mUIБезопасностьHyperlink == null))
                {
                    this.mUIБезопасностьHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIБезопасностьHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIБезопасностьHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIБезопасностьHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIБезопасностьHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Безопасность";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/security";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Безопасность";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://agaveqa.inside.cactussoft.biz/security";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "pull-right cross-link";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Безопасность\" class=\"pull-right c";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIБезопасностьHyperlink.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIБезопасностьHyperlink;
            }
        }
        
        public HtmlHyperlink UIRUHyperlink
        {
            get
            {
                if ((this.mUIRUHyperlink == null))
                {
                    this.mUIRUHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRUHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "lang";
                    this.mUIRUHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRUHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRUHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "RU";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "void(0)";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Choose your Language";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:void(0)";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "language active";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Choose your Language\" class=\"lang";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIRUHyperlink.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIRUHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIВходENБезопасностьТаPane;
        
        private HtmlDiv mUIВходENБезопасностьТаPane1;
        
        private HtmlDiv mUIФункционалПерсонализPane;
        
        private HtmlDiv mUIItem1ПерсонализацияСPane;
        
        private HtmlHyperlink mUIТарифыHyperlink;
        
        private HtmlHyperlink mUIБезопасностьHyperlink;
        
        private HtmlHyperlink mUIRUHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIWispConnectyouremploDocument : HtmlDocument
    {
        
        public UIWispConnectyouremploDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Wisp - Connect your employees to your company’s life";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/admin/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://agaveqa.inside.cactussoft.biz/admin/#/contacts";
            this.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "HEADER";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = null;
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlHyperlink UIBrandNewTestLongNameHyperlink
        {
            get
            {
                if ((this.mUIBrandNewTestLongNameHyperlink == null))
                {
                    this.mUIBrandNewTestLongNameHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBrandNewTestLongNameHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBrandNewTestLongNameHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBrandNewTestLongNameHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBrandNewTestLongNameHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Brand New Test (Long Name Validation)2 test test tes ";
                    this.mUIBrandNewTestLongNameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIBrandNewTestLongNameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBrandNewTestLongNameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "#/company";
                    this.mUIBrandNewTestLongNameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "profile";
                    this.mUIBrandNewTestLongNameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"profile\" href=\"#/company\" ng-href";
                    this.mUIBrandNewTestLongNameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIBrandNewTestLongNameHyperlink.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIBrandNewTestLongNameHyperlink;
            }
        }
        
        public HtmlCustom UIContactsCustom
        {
            get
            {
                if ((this.mUIContactsCustom == null))
                {
                    this.mUIContactsCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIContactsCustom.SearchProperties["TagName"] = "LI";
                    this.mUIContactsCustom.SearchProperties["Id"] = null;
                    this.mUIContactsCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIContactsCustom.FilterProperties["Class"] = "tutorial-area step5 active";
                    this.mUIContactsCustom.FilterProperties["ControlDefinition"] = "class=\"tutorial-area step5 active\" ng-cl";
                    this.mUIContactsCustom.FilterProperties["InnerText"] = "Contacts\r\n ";
                    this.mUIContactsCustom.FilterProperties["TagInstance"] = "2";
                    this.mUIContactsCustom.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIContactsCustom;
            }
        }
        
        public HtmlDiv UIContacts124contactsPane
        {
            get
            {
                if ((this.mUIContacts124contactsPane == null))
                {
                    this.mUIContacts124contactsPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIContacts124contactsPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIContacts124contactsPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIContacts124contactsPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Contacts\r\n  124 contacts ";
                    this.mUIContacts124contactsPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIContacts124contactsPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "page-name-container";
                    this.mUIContacts124contactsPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"page-name-container\"";
                    this.mUIContacts124contactsPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "12";
                    this.mUIContacts124contactsPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIContacts124contactsPane;
            }
        }
        
        public HtmlButton UIAddemployeeButton
        {
            get
            {
                if ((this.mUIAddemployeeButton == null))
                {
                    this.mUIAddemployeeButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIAddemployeeButton.SearchProperties[HtmlButton.PropertyNames.Id] = "add-empl";
                    this.mUIAddemployeeButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAddemployeeButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = " Add employee ";
                    this.mUIAddemployeeButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUIAddemployeeButton.FilterProperties[HtmlButton.PropertyNames.Title] = "Add employee";
                    this.mUIAddemployeeButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn-bd auto-width purple uppercase pull-right ng-binding";
                    this.mUIAddemployeeButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "title=\"Add employee\" class=\"btn-bd auto-";
                    this.mUIAddemployeeButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUIAddemployeeButton.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIAddemployeeButton;
            }
        }
        
        public HtmlEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "filter-area-input pull-left ng-pristine ng-untouched ng-valid ng-valid-minlength " +
                        "ng-valid-maxlength";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"filter-area-input pull-left ng-pr";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIItemEdit.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public UIContactsTable UIContactsTable
        {
            get
            {
                if ((this.mUIContactsTable == null))
                {
                    this.mUIContactsTable = new UIContactsTable(this);
                }
                return this.mUIContactsTable;
            }
        }
        
        public UIContactsTable1 UIContactsTable1
        {
            get
            {
                if ((this.mUIContactsTable1 == null))
                {
                    this.mUIContactsTable1 = new UIContactsTable1(this);
                }
                return this.mUIContactsTable1;
            }
        }
        
        public UIShowcontactAlenaGamoRow UIShowcontactAlenaGamoRow
        {
            get
            {
                if ((this.mUIShowcontactAlenaGamoRow == null))
                {
                    this.mUIShowcontactAlenaGamoRow = new UIShowcontactAlenaGamoRow(this);
                }
                return this.mUIShowcontactAlenaGamoRow;
            }
        }
        
        public HtmlDiv UITagsPane
        {
            get
            {
                if ((this.mUITagsPane == null))
                {
                    this.mUITagsPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUITagsPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUITagsPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUITagsPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Tags\r\n\r\n\r\n\r\n\r\n  ×   ";
                    this.mUITagsPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUITagsPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "right-area-header";
                    this.mUITagsPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"right-area-header\"";
                    this.mUITagsPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "143";
                    this.mUITagsPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUITagsPane;
            }
        }
        
        public HtmlCustom UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom1.SearchProperties["TagName"] = "H3";
                    this.mUIItemCustom1.SearchProperties["Id"] = null;
                    this.mUIItemCustom1.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom1.FilterProperties["Class"] = "ng-binding";
                    this.mUIItemCustom1.FilterProperties["ControlDefinition"] = "class=\"ng-binding\"";
                    this.mUIItemCustom1.FilterProperties["TagInstance"] = "2";
                    this.mUIItemCustom1.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItemCustom1;
            }
        }
        
        public HtmlLabel UIItemLabel
        {
            get
            {
                if ((this.mUIItemLabel == null))
                {
                    this.mUIItemLabel = new HtmlLabel(this);
                    #region Search Criteria
                    this.mUIItemLabel.SearchProperties[HtmlLabel.PropertyNames.Id] = null;
                    this.mUIItemLabel.SearchProperties[HtmlLabel.PropertyNames.Name] = null;
                    this.mUIItemLabel.SearchProperties[HtmlLabel.PropertyNames.LabelFor] = "search-tag";
                    this.mUIItemLabel.SearchProperties[HtmlLabel.PropertyNames.InnerText] = " × ";
                    this.mUIItemLabel.FilterProperties[HtmlLabel.PropertyNames.Class] = "mdl-button mdl-js-button mdl-button--icon right";
                    this.mUIItemLabel.FilterProperties[HtmlLabel.PropertyNames.ControlDefinition] = "title=\"Search Tags\" class=\"mdl-button md";
                    this.mUIItemLabel.FilterProperties[HtmlLabel.PropertyNames.TagInstance] = "161";
                    this.mUIItemLabel.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItemLabel;
            }
        }
        
        public HtmlEdit UIItemEdit1
        {
            get
            {
                if ((this.mUIItemEdit1 == null))
                {
                    this.mUIItemEdit1 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit1.SearchProperties[HtmlEdit.PropertyNames.Id] = "search-tag";
                    this.mUIItemEdit1.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIItemEdit1.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = " × ";
                    this.mUIItemEdit1.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIItemEdit1.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIItemEdit1.FilterProperties[HtmlEdit.PropertyNames.Class] = "mdl-textfield__input ng-pristine ng-untouched ng-valid";
                    this.mUIItemEdit1.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"mdl-textfield__input ng-pristine ";
                    this.mUIItemEdit1.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "162";
                    this.mUIItemEdit1.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItemEdit1;
            }
        }
        
        public HtmlDiv UIItem11Pane
        {
            get
            {
                if ((this.mUIItem11Pane == null))
                {
                    this.mUIItem11Pane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItem11Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItem11Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItem11Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "1 \r\n\r\n× \r\n\r\n\r\n\r\n\r\n\r\n  \r\n 1 \r\n\r\n× \r\n\r\n\r\n\r";
                    this.mUIItem11Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItem11Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = "nzScrollbar-inner";
                    this.mUIItem11Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"nzScrollbar-inner\" style=\"position: relative; transform: translateY(0px);\"" +
                        " ng-transclude=\"\"";
                    this.mUIItem11Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "149";
                    this.mUIItem11Pane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItem11Pane;
            }
        }
        
        public HtmlDiv UIItem1Pane
        {
            get
            {
                if ((this.mUIItem1Pane == null))
                {
                    this.mUIItem1Pane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItem1Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItem1Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItem1Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "1 \r\n\r\n× ";
                    this.mUIItem1Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItem1Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = "stripe editable ng-scope";
                    this.mUIItem1Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"stripe editable ng-scope\" ng-repeat=\"tag in userTags | filter:searchElRigh" +
                        "t\"";
                    this.mUIItem1Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "150";
                    this.mUIItem1Pane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItem1Pane;
            }
        }
        
        public HtmlEdit UIItemEdit2
        {
            get
            {
                if ((this.mUIItemEdit2 == null))
                {
                    this.mUIItemEdit2 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit2.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIItemEdit2.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIItemEdit2.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIItemEdit2.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIItemEdit2.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIItemEdit2.FilterProperties[HtmlEdit.PropertyNames.Class] = "transparent-editable ng-pristine ng-untouched ng-valid ng-valid-minlength ng-vali" +
                        "d-maxlength";
                    this.mUIItemEdit2.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"transparent-editable ng-pristine ";
                    this.mUIItemEdit2.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "163";
                    this.mUIItemEdit2.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItemEdit2;
            }
        }
        
        public HtmlSpan UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "×";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = "Delete tag";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "ng-isolate-scope";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "title=\"Delete tag\" class=\"ng-isolate-scope\" ng-really-click=\"deleteTag(tag.Name)\"" +
                        " ng-really-message=\"Are you sure you want to delete this tag?\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "169";
                    this.mUIItemPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public HtmlSpan UIItem1Pane1
        {
            get
            {
                if ((this.mUIItem1Pane1 == null))
                {
                    this.mUIItem1Pane1 = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIItem1Pane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItem1Pane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItem1Pane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "1";
                    this.mUIItem1Pane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItem1Pane1.FilterProperties[HtmlDiv.PropertyNames.Class] = "count ng-binding";
                    this.mUIItem1Pane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"count ng-binding\"";
                    this.mUIItem1Pane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "168";
                    this.mUIItem1Pane1.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItem1Pane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        
        private HtmlHyperlink mUIBrandNewTestLongNameHyperlink;
        
        private HtmlCustom mUIContactsCustom;
        
        private HtmlDiv mUIContacts124contactsPane;
        
        private HtmlButton mUIAddemployeeButton;
        
        private HtmlEdit mUIItemEdit;
        
        private UIContactsTable mUIContactsTable;
        
        private UIContactsTable1 mUIContactsTable1;
        
        private UIShowcontactAlenaGamoRow mUIShowcontactAlenaGamoRow;
        
        private HtmlDiv mUITagsPane;
        
        private HtmlCustom mUIItemCustom1;
        
        private HtmlLabel mUIItemLabel;
        
        private HtmlEdit mUIItemEdit1;
        
        private HtmlDiv mUIItem11Pane;
        
        private HtmlDiv mUIItem1Pane;
        
        private HtmlEdit mUIItemEdit2;
        
        private HtmlSpan mUIItemPane;
        
        private HtmlSpan mUIItem1Pane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContactsTable : HtmlTable
    {
        
        public UIContactsTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "contacts";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "First Name\r\n\r\n\r\nLast Name\r\n\r\n\r\nPosition\r";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"table table-striped table-hover contacts-table thead for-scrolled\" id=\"con" +
                "tacts\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table table-striped table-hover contacts-table thead for-scrolled";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
            #endregion
        }
        
        #region Properties
        public HtmlHeaderCell UIFirstNameLastNamePosCell
        {
            get
            {
                if ((this.mUIFirstNameLastNamePosCell == null))
                {
                    this.mUIFirstNameLastNamePosCell = new HtmlHeaderCell(this);
                    #region Search Criteria
                    this.mUIFirstNameLastNamePosCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIFirstNameLastNamePosCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIFirstNameLastNamePosCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIFirstNameLastNamePosCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "First Name\r\n\r\n\r\nLast Name\r\n\r\n\r\nPosition\r";
                    this.mUIFirstNameLastNamePosCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"first-th-contacts-column\" colspan=\"2\"";
                    this.mUIFirstNameLastNamePosCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIFirstNameLastNamePosCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIFirstNameLastNamePosCell.FilterProperties[HtmlCell.PropertyNames.Class] = "first-th-contacts-column";
                    this.mUIFirstNameLastNamePosCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1";
                    this.mUIFirstNameLastNamePosCell.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIFirstNameLastNamePosCell;
            }
        }
        
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "header-checkbox";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"header-checkbox\" ng-click=\"checkAll(); checkBoxSelected()\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "18";
                    this.mUIItemPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public HtmlButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIItemButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIItemButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = " ";
                    this.mUIItemButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUIItemButton.FilterProperties[HtmlButton.PropertyNames.Title] = "Change Sorting Order";
                    this.mUIItemButton.FilterProperties[HtmlButton.PropertyNames.Class] = "dropdown-toggle sorting";
                    this.mUIItemButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "title=\"Change Sorting Order\" class=\"drop";
                    this.mUIItemButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIItemButton.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public HtmlHyperlink UIDeletecontactsHyperlink
        {
            get
            {
                if ((this.mUIDeletecontactsHyperlink == null))
                {
                    this.mUIDeletecontactsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDeletecontactsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDeletecontactsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDeletecontactsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDeletecontactsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = null;
                    this.mUIDeletecontactsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "void(0)";
                    this.mUIDeletecontactsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Delete contacts";
                    this.mUIDeletecontactsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:void(0)";
                    this.mUIDeletecontactsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "trash-icon ng-isolate-scope disabled";
                    this.mUIDeletecontactsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Delete contacts\" class=\"trash-ico";
                    this.mUIDeletecontactsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "5";
                    this.mUIDeletecontactsHyperlink.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIDeletecontactsHyperlink;
            }
        }
        
        public HtmlHeaderCell UIImportExportSendQRcoCell
        {
            get
            {
                if ((this.mUIImportExportSendQRcoCell == null))
                {
                    this.mUIImportExportSendQRcoCell = new HtmlHeaderCell(this);
                    #region Search Criteria
                    this.mUIImportExportSendQRcoCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIImportExportSendQRcoCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIImportExportSendQRcoCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIImportExportSendQRcoCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Import\r\n\r\n\r\nExport\r\n\r\nSend QR-code  Send";
                    this.mUIImportExportSendQRcoCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"no-padding to-hide\" colspan=\"3\"";
                    this.mUIImportExportSendQRcoCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIImportExportSendQRcoCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "1";
                    this.mUIImportExportSendQRcoCell.FilterProperties[HtmlCell.PropertyNames.Class] = "no-padding to-hide";
                    this.mUIImportExportSendQRcoCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "2";
                    this.mUIImportExportSendQRcoCell.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIImportExportSendQRcoCell;
            }
        }
        
        public HtmlDiv UIImportExportPane
        {
            get
            {
                if ((this.mUIImportExportPane == null))
                {
                    this.mUIImportExportPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIImportExportPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIImportExportPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIImportExportPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Import\r\n\r\n\r\nExport";
                    this.mUIImportExportPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIImportExportPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "btn-group pull-right tutorial-area step8";
                    this.mUIImportExportPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"btn-group pull-right tutorial-area step8\"";
                    this.mUIImportExportPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "20";
                    this.mUIImportExportPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIImportExportPane;
            }
        }
        
        public HtmlButton UISendQRcodeButton
        {
            get
            {
                if ((this.mUISendQRcodeButton == null))
                {
                    this.mUISendQRcodeButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUISendQRcodeButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUISendQRcodeButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISendQRcodeButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Send QR-code ";
                    this.mUISendQRcodeButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUISendQRcodeButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISendQRcodeButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn-bd white pull-right ng-binding disabled";
                    this.mUISendQRcodeButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn-bd white pull-right ng-bindin";
                    this.mUISendQRcodeButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUISendQRcodeButton.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUISendQRcodeButton;
            }
        }
        
        public HtmlButton UIAddtagsButton
        {
            get
            {
                if ((this.mUIAddtagsButton == null))
                {
                    this.mUIAddtagsButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIAddtagsButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIAddtagsButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAddtagsButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Add tags ";
                    this.mUIAddtagsButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUIAddtagsButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAddtagsButton.FilterProperties[HtmlButton.PropertyNames.Class] = "dropdown-toggle btn-bd white pull-right ng-binding disabled";
                    this.mUIAddtagsButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"dropdown-toggle btn-bd white pull";
                    this.mUIAddtagsButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "5";
                    this.mUIAddtagsButton.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIAddtagsButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHeaderCell mUIFirstNameLastNamePosCell;
        
        private HtmlDiv mUIItemPane;
        
        private HtmlButton mUIItemButton;
        
        private HtmlHyperlink mUIDeletecontactsHyperlink;
        
        private HtmlHeaderCell mUIImportExportSendQRcoCell;
        
        private HtmlDiv mUIImportExportPane;
        
        private HtmlButton mUISendQRcodeButton;
        
        private HtmlButton mUIAddtagsButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIContactsTable1 : HtmlTable
    {
        
        public UIContactsTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "contacts";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Alena Gamolko \r\n\r\nInternet Marketing Dir";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = @"class=""table table-striped table-hover contacts-table is-scrolled js-contacts-list ng-isolate-scope nzScrollbar"" id=""contacts"" nz-scrollbar="""" infinite-scroll-listen-for-event=""content.reachedBottom"" infinite-scroll-container='"".js-contacts-list .nzScrollbar-inner""' infinite-scroll-distance=""3"" infinite-scroll=""getEventsByScroll()"" scroll-margin=""700"" use-css-translate=""false""";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "0";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "0";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table table-striped table-hover contacts-table is-scrolled js-contacts-list ng-is" +
                "olate-scope nzScrollbar";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIAlenaGamolkoInternetPane
        {
            get
            {
                if ((this.mUIAlenaGamolkoInternetPane == null))
                {
                    this.mUIAlenaGamolkoInternetPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAlenaGamolkoInternetPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAlenaGamolkoInternetPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAlenaGamolkoInternetPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Alena Gamolko \r\n\r\nInternet Marketing Dir";
                    this.mUIAlenaGamolkoInternetPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAlenaGamolkoInternetPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "nzScrollbar-inner";
                    this.mUIAlenaGamolkoInternetPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"nzScrollbar-inner\" style=\"top: 0px; position: relative;\" ng-transclude=\"\"";
                    this.mUIAlenaGamolkoInternetPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "33";
                    this.mUIAlenaGamolkoInternetPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIAlenaGamolkoInternetPane;
            }
        }
        
        public HtmlCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"tag-info\" ng-click=\"openItemDetails(user)\"";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "3";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.Class] = "tag-info";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "4";
                    this.mUIItemCell.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIAlenaGamolkoInternetPane;
        
        private HtmlCell mUIItemCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIShowcontactAlenaGamoRow : HtmlRow
    {
        
        public UIShowcontactAlenaGamoRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlRow.PropertyNames.Id] = "55e98c51743fdb54b8a68d5c";
            this.SearchProperties[HtmlRow.PropertyNames.Name] = null;
            this.FilterProperties[HtmlRow.PropertyNames.InnerText] = "Alena Gamolko \r\n\r\nInternet Marketing Dir";
            this.FilterProperties[HtmlRow.PropertyNames.ControlDefinition] = "title=\"Show contact Alena Gamolko\" class=\"table-row ng-scope\" id=\"55e98c51743fdb5" +
                "4b8a68d5c\" ng-class=\"{\'hover-table-effect\': person.Id == user.Id}\" ng-repeat=\"us" +
                "er in renderedUsers | orderBy:predicate:reverse\"";
            this.FilterProperties[HtmlRow.PropertyNames.RowIndex] = "0";
            this.FilterProperties[HtmlRow.PropertyNames.Class] = "table-row ng-scope";
            this.FilterProperties[HtmlRow.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIAvatarImage
        {
            get
            {
                if ((this.mUIAvatarImage == null))
                {
                    this.mUIAvatarImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIAvatarImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIAvatarImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIAvatarImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Avatar";
                    this.mUIAvatarImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/admin/images/png/avatar_148_148.7829bb96.png";
                    this.mUIAvatarImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://agaveqa.inside.cactussoft.biz/admin/images/png/avatar_148_148.7829bb96.pn" +
                        "g";
                    this.mUIAvatarImage.FilterProperties[HtmlImage.PropertyNames.Class] = "img-responsive center-block action";
                    this.mUIAvatarImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "class=\"img-responsive center-block actio";
                    this.mUIAvatarImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIAvatarImage.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIAvatarImage;
            }
        }
        
        public HtmlLabel UIItemLabel
        {
            get
            {
                if ((this.mUIItemLabel == null))
                {
                    this.mUIItemLabel = new HtmlLabel(this);
                    #region Search Criteria
                    this.mUIItemLabel.SearchProperties[HtmlLabel.PropertyNames.Id] = null;
                    this.mUIItemLabel.SearchProperties[HtmlLabel.PropertyNames.Name] = null;
                    this.mUIItemLabel.SearchProperties[HtmlLabel.PropertyNames.LabelFor] = "qr-checkbox-table-55e98c51743fdb54b8a68d5c";
                    this.mUIItemLabel.SearchProperties[HtmlLabel.PropertyNames.InnerText] = null;
                    this.mUIItemLabel.FilterProperties[HtmlLabel.PropertyNames.Class] = null;
                    this.mUIItemLabel.FilterProperties[HtmlLabel.PropertyNames.ControlDefinition] = "for=\"qr-checkbox-table-55e98c51743fdb54b";
                    this.mUIItemLabel.FilterProperties[HtmlLabel.PropertyNames.TagInstance] = "1";
                    this.mUIItemLabel.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItemLabel;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIAvatarImage;
        
        private HtmlLabel mUIItemLabel;
        #endregion
    }
}
